library(Simba4Bioc)
library(ggplot2)
library(plotly)
ref = simba_ref()
t3k = get_10x3kpbmc_path()
newad = ref$read_h5ad(t3k)
bb = basic_preproc(newad, simba_ref=ref)
cc = build_and_train_pbg(bb, simba_ref=ref)
dd = ref$read_embedding()
ee = propagate_label( ref, newad, "celltype")
library(uwot)
ff = umap(ee['X'])
mydf = data.frame(x=ff[,1], y=ff[,2], type=ee$obs[, "celltype"])
p1 = ggplot(mydf, aes(x=x, y=y, colour=type)) + geom_point()
library(plotly)
ggplotly(p1)
